#!/bin/sh
pwd=`pwd`
java -jar -DAPP_HOME="$pwd/" target/scala-2.10/weather-challenge-assembly-1.0.jar <&- &
echo "****************************************"
echo "***********  WISHCLOUDS API  ***********"
echo "***********   started $!   ***********"
echo "****************************************"
pid=$!
echo ${pid} > deamon.pid